services:
  promtail:
    image: grafana/promtail:latest
    container_name: Promtail
    ports:
      - "9080:9080"
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ../Backend/docker/promtail/promtail-config.yaml:/etc/promtail/custom-config.yaml
      - ../Backend/logs:/var/log/django:ro
      - /etc/localtime:/etc/localtime:ro
    command: -config.file=/etc/promtail/custom-config.yaml
    privileged: true


  loki:
    image: grafana/loki:latest
    container_name: Loki
    ports:
      - "3100:3100"
    volumes:
      - ../Backend/docker/loki/loki-config.yaml:/etc/loki/custom-config.yaml
    command: -config.file=/etc/loki/custom-config.yaml
    
  prometheus:
    image: prom/prometheus:latest
    container_name: Prometheus
    ports:
      - "9090:9090"
    volumes:
      - ../Backend/docker/prometheus/prometheus.yml:/etc/prometheus/custom-prometheus.yml
      - prometheusdata:/prometheus
      - /etc/localtime:/etc/localtime:ro
    command:
      - --config.file=/etc/prometheus/custom-prometheus.yml


  grafana:
    image: grafana/grafana:latest
    container_name: Grafana
    ports:
      - "3001:3001"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ../Backend/docker/grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - grafanadata:/var/lib/grafana
      - /etc/localtime:/etc/localtime:ro

  backend:
    build:
      context: ../Backend   # контекст — весь backend
      dockerfile: docker/Dockerfile  # Dockerfile внутри backend/docker
    container_name: Backend
    ports:
      - "8000:8000"
    env_file:
      - ../Backend/.env
    volumes:
      - ../Backend/media:/app/media
      - /etc/localtime:/etc/localtime:ro

    logging:
      driver: json-file
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"

  frontend:
    build:
      context: .
      args:
        REACT_APP_BACKEND_API_URL: http://localhost:8000
    container_name: Frontend
    ports:
      - "3000:80"
    volumes:
      - /etc/localtime:/etc/localtime:ro


volumes:
  grafanadata:
  prometheusdata:
